os:
- linux
services:
- docker
language: node_js
node_js:
- 6.11.1
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.11.1
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - secure: BlgGnHnsEVbYuB8981OYkiOQCQfqthAoKXjNQH3AX9y4fxqFSK4UoHNoFoUyAg8aP5yIuKlvB8Y5vCHFpZKqXMNpfgzgh0CAvT/iuQkZXhjILnIUsXaqoZCrlTFfi/vN4SuvCxGHY3pzV1hwtF5wV+uklUP6a8P3Z6zd4tlW8HWPnCootqp9vK2xPwIf9X2ei0gKlTvMunyTOeTE4+HIZeBcwT6Tp7X9Desg+ijSykHLz5kkK1LUxiqmAQ7kPQpNLLVwnSJAQtSzp/IE1AiI6jMxSHUfGeyoZSFiAtRGAKPEFMQnZp7Lo/rb96dlWB9K1FSjo1BwL91K28k0QChdYlnQ7syKfRzxoIr2TiZEzMrcZBx8+m/Bg/wLfWZcWquFZwylpGD9YutcXSPUJfUcR7jKS3OyETucjNmQmfuEMoHj6HpZGKqDREsXrEkR6CYDUnResKzBcGQqgX4ywjqgpa50FNfg3gBTevL2ubkV2b3gNoKj+BJcjKlBIh9XPGcz1+Zz5rahj99Evlp4BRDZuccEF3OPM3dOywQDiDVrhxCVVyl6lbSG1tmTp6uiXwdfh3IuFip53JxvKU0YWP4eb88RwSitZsNz9GyOF19IzFAQmzycp08fcpvds1t3WBvm0sAKQ/Qt+IwJQ4K9XUOoK4ph4o9Qml6TOrM0agAFKP8=
  - secure: lYf4amMLXMN61BalmQvvLYhV8Pj1km1LaViVINWHO1A/T1j/qfa8vdubL3kG21OZDTPZHxEgq69/jBldN2djssVtAcn3c30zvFJUdJDzcmAQlhBFgK4aw4N8HU3d63Ey1Ky5rrnMrjYUCDvs45qD3b+7KWcGNO8mj22nHmDzljm2PjQ9bOL+rGvk7+HA05GF/v9NcXl2L3YXbayYHRCYY0ChQDfv5279pjYs2j4rlJO3Itv/n5/OYbQZ8owE4Z4lgN+boPvlqBU+/isUwE9MLS/rbS+GHhB5b1sNoCc5SPWa8qONyfTxHzM4wIB2vUF3nU/LaZtsZNqCn0PsCaLVufZQsOJTv1/0QojChob9fK5Q3kv63DfI4zh8v9aoCSBUdV+vp5AspyoJmyBTKDXXC/zk8Y70/RLcnutVhVX2NE3QXbsGsFmqGp1RkBBlCsqTPzB3lEoCjXrhYue8Bl2TpBPVJmonOu5odWMlLiMA5QFy8mRxXBmwMm+hI0M/cp5cVlBj1ytXeq7jxk/bpOcRI7dvheT9yDAXteMUds3t+A0QMLbZOtwqJGQatNBigfXFgVr2BXcdbG3HzVFCRcO7aREYLYKa/TvciPSqG2P2cTGJj5SpxBqnApU/Xs/dmIHEwIs+WstC/xiS1YCkAGR8ZKNS7J3a65+CbiFx+vdOSoY=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw package -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
before_deploy:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region eu-west-1)
- "./mvnw verify -Pprod -DskipTests dockerfile:build"
- docker tag kransenzo:latest 455637595802.dkr.ecr.eu-west-1.amazonaws.com/kransenzo:latest
- docker push 455637595802.dkr.ecr.eu-west-1.amazonaws.com/kransenzo:latest
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJL4FMHJ4MPMN2ZSQ
  secret_access_key:
    secure: V03k+vnA/q9+9/8DBFVy6GVJ2Bcoz4gP7AzoMh46kHBUQGR5hCkjG3M3EoXY+kpj9COMrIgKpY+TGj3DDjHMAOXjctp5P6VE94crNd4ZFNznzAfRYcu4KcWdqp8dKLyNZ5oDhiReGS3DI6g87mKlJR+BW9L1GUYnJn5JEE/8DimwyImvlkVIOUGTIlbZvik+ulrpE+NggmqMwZ8XB58aHu7wkiOz/dj7uB56IWRMXGAYWlS4FH6zEDP2l/tyy4bQru+T7Cnyz3Gs1yLp/VmQLjNZJjgf+5V6kXft/wSbm2gWam7eTx2ddxwS9FgHSMv8rliey6E8EUc1A22D91S0soykhHDfr3G1NlBNOvaN1uoEkJamQmOi6FutHf2uk8HcIWOV77JC7Zzhyr91uI8Ah4+gY5GqVvcfS1TlVy2CBXV26vIMF2Dii6u3COGwEEAZbtw3X5it31Eicpimxn6BVcNvD/uIpMeQKozWcS69fpk7QHicNFU3kmhOk070Sm1BxhUbHapq6dm/zUqTMcz6Wh1M5LWeANbRxm7yAUIlmhBm+1jxjXCLVXSzw5+yZEz08zjb8WpGzoMM9fOXfsSUGdG5WrPTdh4ERlp7hibpXwXpNfPIVQ0ZJgrZs0wkdcrqFVCFFtMNudj1BMqA9jhHj/dO86DXI7Jtvqn4hiZ2RCo=
  region: eu-west-1
  app: kransenzo
  env: live
  on:
    repo: sandervanloock/kransenzo
