os:
- linux
services:
- docker
language: node_js
node_js:
- 6.11.1
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.11.1
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - secure: OEbg9wpeGhFi9+kvoyQofn3QXSZAPvsCxk4Nit4pERmEe93TE1XwHh0RUyIY9Nx2qTxyhPnIXKZNjpw5eGMtqLEjyx2h8CLC/C3NjRiMtoo+CBr3bnZfv8Ff3XixKIdOsiuDvcmzgeiDfo5UUCSxulaj8A9Ydn1qloFG0O7BdxbgE+emwqWTLos6K0awcEBoaJlI2TmmukgsaZRfxjWQasVBFiMGDv1Sj1PM48P+uyBXJApkTcgluk35ggyBD6mTesJqT0aevYeMzu4tIFpZeBPSVBPgc1jiCIhh7C0khb84xFgvhPDrvV2rAteeBgDCTBhmjk9+7C3pNSNnP9YgSYC0aRaxiF2sgpVzATm5w0dAihjKJ02YX1sKKlvVw6gZDDngDJUECwY3OpCOJlpCTlQI82bTC9p7hS44IFCisZtSmGE1KWbN1Ji8GGIUuyRQLf0vdMpE9SKl7Xf86Qfwt6GGDWozF1cVJT23YgzxpSvGw+EJzag7T2D/frba/PZaLed0wwwkeNUj6XdLSwQ3NO0XdZm6yNWyS5Csenii2+oKey2hB+++LSGi2JdzJHWNOLGDNUpQb5ben6/SxF7b09GgLamtIW98SScUSSnkvw0cjtl0+FOKHXbmgvuDIdfR0wG5llseTEO0YlBoidntnrNUB5xppcRTOqpsptcFOlg=
  - secure: cHPvBvkXFC+7ATNsUoFALsRO9uTP6joO5BPf77cOwQp4z47dmTiCROU2ohh6s7Wtd1mGBTJ5xgwdUZQESDjpHJd9YEXsdHl5LWG8lo0YP8/Vdhc8Lc/S1O6TlOmPQk3+G/E1MLgnkc+gJuRH1kYvTRdn2ky5AGo0okp05DHNC8uJ29rA6FsXqWYk3hKoLgtz1md+ocxdCLTq1pZHr70kmzD9XNvfsp8Cxf5IjJEecMKZBmGlz4CyI9WCJZmE0AVoVTq+L3hcBlwgeB4B69KD1daOzlW+AQIMd1fB1pG9OyquWZGYF7PQ0IcIGCNYfUxd5br1qHPiTkP3+3kaPd29J3MdH4zrixnnUh94NLbeQ0wkcmBrw2BB1vCZMl0KyRGInhAwZTFcvZW0dT9FYvuFOGxhQxLoBZWaw+ETBkWh6Op+M1RPnq95V/oyTBEO6T8Fs5BhUzVpqQMSXSLrgmTwmJEH5iOq/8BdpwBtZk/vy3K+qVbb7KJvgn4tZNKfNSJIzY47FQ+usJ0sVGwmZO2UI8YLgAQ6E1bfiLnqODwEkeJ+Sb3JpHXpwsmy7unhmKDx4CJqbQ40XSEoPbPSaamblgDXroobuEbwdpinZ/QxLL6lL80xdOFpR32ESlOAYsVc2fHZZfbyqYRL6WVEkgOGBRFfwwMPvFc3NP9W218In1M=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw package -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false

after_success:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region eu-west-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - ./mvnw verify -Pprod -DskipTests dockerfile:build
  - docker tag kransenzo:latest 455637595802.dkr.ecr.eu-west-1.amazonaws.com/kransenzo:latest
  - docker push 455637595802.dkr.ecr.eu-west-1.amazonaws.com/kransenzo:latest
