branch-defaults:
  import-jdl:
    environment: prod
    group_suffix: null
global:
  application_name: kransenzo
  branch: null
  default_ec2_keyname: ec2-sandervl-amazon
  default_platform: Docker 17.06.2-ce
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: jhipster
  repository: null
  sc: git
  workspace_type: Application
