version: "3.9"
services:
    db:
        image: "mysql:8.0.23"
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
